Avoid crash when sending from inactive keyper
Previously keypers would crash, when trying to send a batch config to
shuttermint ahead of time, with the crash log

```
Error: remote error: checktx: not a keyper set member
remote error: checktx: not a keyper set member
```

With these changes, keypers will

a) check, if they are known to shuttermint, and therefore allowed to
send messages.

b) keep messages that failed to send in the outgoing message queue.

This is part of #465